TABLE_ (ISSUELOG)
    INT_	(ID) PRIMARY_KEY

	INT_	(OLD_STORING_ID)

    INT_	(PERSON)	INDEX REFERENCES (PERSONS)
    INT_	(ACTIVITY)	INDEX REFERENCES (ACTIVITIES)
    INT_	(ISSUETYPE) INDEX REFERENCES (ISSUETYPES)
    INT_	(MACHINE) INDEX REFERENCES (MACHINES)
    
    BLOB_	(ISSUE)
    BLOB_	(CAUSE)
	BLOB_	(SOLUTION)
	BLOB_	(REMARK)
    
    DATE_	(DAY)
	INT_	(SHIFT)
    INT_	(MINUTES)
END_TABLE

TABLE_ (PERSONS)
    INT_	(P_ID) PRIMARY_KEY
    BOOL_	(P_ACTIVE)
    INT_	(P_NUMBER)
    STRING_	(FIRST_NAME, 30)
    STRING_	(MID_NAME, 10)
    STRING_	(LAST_NAME, 30)
END_TABLE

TABLE_ (ACTIVITIES)
	INT_	(ACT_ID) PRIMARY_KEY
	BOOL_	(ACT_ACTIVE)
	STRING_ (ACT_SHORT,10)
	STRING_ (ACT_LONG,30)
END_TABLE
 
TABLE_ (ISSUETYPES)
	INT_	(TYPE_ID) PRIMARY_KEY
	BOOL_	(TYPE_ACTIVE)
	STRING_	(TYPE_SHORT,10)
	STRING_	(TYPE_LONG,30)
END_TABLE

TABLE_ (MACHINES)
	INT_	(M_ID) PRIMARY_KEY
	BOOL_	(M_ACTIVE)
	INT_	(LINE) REFERENCES (LINES)
	INT_	(MACHINETYPE) REFERENCES (MACHINETYPES)
	STRING_	(MACHINE_DESCRIPTION, 40)
END_TABLE

TABLE_ (MACHINETYPES)
	INT_	(MTYPE_ID) PRIMARY_KEY
	BOOL_	(MTYPE_ACTIVE)
	STRING_	(MTYPE_DESCRIPTION, 40)
END_TABLE

TABLE_ (LINES)
	INT_	(L_ID) PRIMARY_KEY
	BOOL_	(L_ACTIVE)
	INT_	(DEPARTMENT) REFERENCES (DEPARTMENTS)
	INT_	(LINE_NUMBER)
	STRING_	(LINE_DESCRIPTION, 30)
END_TABLE

TABLE_ (DEPARTMENTS)
	INT_	(DEP_ID) PRIMARY_KEY
	BOOL_	(DEP_ACTIVE)
	STRING_	(DEP_SHORT, 10)
	STRING_	(DEP_LONG, 30)
END_TABLE
